import { Inter } from 'next/font/google'
import './globals.css'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
import { ClerkProvider, SignInButton, SignOutButton } from '@clerk/nextjs'
import {UserButton} from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex  h-16 justify-between items-center p-4 border-2 border-black">
          <div className="text-l font-bold"><Link href={'/'}>LOGO</Link></div>
          <div className="flex gap-x-3">
            
            <SignInButton className="bg-blue-500 hover:bg-blue-700 text-white  py-2 px-6 rounded-lg shadow-md" />
            <SignOutButton className="bg-red-500 hover:bg-red-700 text-white  py-2 px-6 rounded-lg shadow-md"/>
            <UserButton/>
          </div>
        </nav>

        {children}



        </body>
    </html>
    </ClerkProvider>
  )
}
